// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

public partial class Score
{
    [Key]
    public int SBD { get; set; }

    public double? Toan { get; set; }

    public double? Van { get; set; }

    public double? Ly { get; set; }

    public double? Sinh { get; set; }

    [Column("Ngoai ngu")]
    public double? Ngoai_ngu { get; set; }

    public int? Year { get; set; }

    public double? Hoa { get; set; }

    [Column("Lich su")]
    public double? Lich_su { get; set; }

    [Column("Dia ly")]
    public double? Dia_ly { get; set; }

    public double? GDCD { get; set; }

    public int? MaTinh { get; set; }
}